package com.room.model;

// Generated 2017-2-14 17:11:29 by Hibernate Tools 4.3.1

/**
 * ManCategories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String cateName;
	private String cateNameCn;
	private Integer parentId;

	public Categories() {
	}

	public Categories(String cateName, Integer parentId) {
		this.cateName = cateName;
		this.parentId = parentId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCateName() {
		return this.cateName;
	}

	public void setCateName(String cateName) {
		this.cateName = cateName;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getCateNameCn() {
		return cateNameCn;
	}

	public void setCateNameCn(String cateNameCn) {
		this.cateNameCn = cateNameCn;
	}

}
