package com.room.model;

import java.util.UUID;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.room.utils.UUIDAdapter;

// Generated 2017-3-1 17:10:45 by Hibernate Tools 3.4.0.CR1

/**
 * ItemTags generated by hbm2java
 */
public class ItemTags implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@XmlJavaTypeAdapter(UUIDAdapter.class)
	private UUID itemId;
	private String tag;

	public ItemTags() {
	}

	public ItemTags(UUID itemId, String tag) {
		this.itemId = itemId;
		this.tag = tag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UUID getItemId() {
		return this.itemId;
	}

	public void setItemId(UUID itemId) {
		this.itemId = itemId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

}
